/*
 * Argo Events
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.events.models.sensor;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.events.models.sensor.TriggerParameter;
import io.kubernetes.client.openapi.models.V1SecretKeySelector;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AzureEventHubsTrigger
 */
public class AzureEventHubsTriggerTest {
    private final AzureEventHubsTrigger model = new AzureEventHubsTrigger();

    /**
     * Model tests for AzureEventHubsTrigger
     */
    @Test
    public void testAzureEventHubsTrigger() {
        // TODO: test AzureEventHubsTrigger
    }

    /**
     * Test the property 'hubName'
     */
    @Test
    public void hubNameTest() {
        // TODO: test hubName
    }

    /**
     * Test the property 'parameters'
     */
    @Test
    public void parametersTest() {
        // TODO: test parameters
    }

    /**
     * Test the property 'fqdn'
     */
    @Test
    public void fqdnTest() {
        // TODO: test fqdn
    }

    /**
     * Test the property 'sharedAccessKey'
     */
    @Test
    public void sharedAccessKeyTest() {
        // TODO: test sharedAccessKey
    }

    /**
     * Test the property 'sharedAccessKeyName'
     */
    @Test
    public void sharedAccessKeyNameTest() {
        // TODO: test sharedAccessKeyName
    }

    /**
     * Test the property 'payload'
     */
    @Test
    public void payloadTest() {
        // TODO: test payload
    }

}
