/*
 * Argo Events
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.events.models.sensor;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.events.models.sensor.ConditionsResetByTime;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ConditionsResetCriteria
 */
public class ConditionsResetCriteriaTest {
    private final ConditionsResetCriteria model = new ConditionsResetCriteria();

    /**
     * Model tests for ConditionsResetCriteria
     */
    @Test
    public void testConditionsResetCriteria() {
        // TODO: test ConditionsResetCriteria
    }

    /**
     * Test the property 'byTime'
     */
    @Test
    public void byTimeTest() {
        // TODO: test byTime
    }

}
