/*
 * Argo Events
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.events.models.sensor;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.events.models.sensor.TriggerParameter;
import io.kubernetes.client.openapi.models.V1SecretKeySelector;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CustomTrigger
 */
public class CustomTriggerTest {
    private final CustomTrigger model = new CustomTrigger();

    /**
     * Model tests for CustomTrigger
     */
    @Test
    public void testCustomTrigger() {
        // TODO: test CustomTrigger
    }

    /**
     * Test the property 'serverNameOverride'
     */
    @Test
    public void serverNameOverrideTest() {
        // TODO: test serverNameOverride
    }

    /**
     * Test the property 'secure'
     */
    @Test
    public void secureTest() {
        // TODO: test secure
    }

    /**
     * Test the property 'parameters'
     */
    @Test
    public void parametersTest() {
        // TODO: test parameters
    }

    /**
     * Test the property 'spec'
     */
    @Test
    public void specTest() {
        // TODO: test spec
    }

    /**
     * Test the property 'certFilePath'
     */
    @Test
    public void certFilePathTest() {
        // TODO: test certFilePath
    }

    /**
     * Test the property 'serverURL'
     */
    @Test
    public void serverURLTest() {
        // TODO: test serverURL
    }

    /**
     * Test the property 'certSecret'
     */
    @Test
    public void certSecretTest() {
        // TODO: test certSecret
    }

    /**
     * Test the property 'payload'
     */
    @Test
    public void payloadTest() {
        // TODO: test payload
    }

}
