/*
 * Argo Events
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.events.models.sensor;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.events.models.sensor.GitCreds;
import io.argoproj.events.models.sensor.GitRemoteConfig;
import io.kubernetes.client.openapi.models.V1SecretKeySelector;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for GitArtifact
 */
public class GitArtifactTest {
    private final GitArtifact model = new GitArtifact();

    /**
     * Model tests for GitArtifact
     */
    @Test
    public void testGitArtifact() {
        // TODO: test GitArtifact
    }

    /**
     * Test the property 'remote'
     */
    @Test
    public void remoteTest() {
        // TODO: test remote
    }

    /**
     * Test the property 'filePath'
     */
    @Test
    public void filePathTest() {
        // TODO: test filePath
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'sshKeyPath'
     */
    @Test
    public void sshKeyPathTest() {
        // TODO: test sshKeyPath
    }

    /**
     * Test the property 'tag'
     */
    @Test
    public void tagTest() {
        // TODO: test tag
    }

    /**
     * Test the property 'sshKeySecret'
     */
    @Test
    public void sshKeySecretTest() {
        // TODO: test sshKeySecret
    }

    /**
     * Test the property 'cloneDirectory'
     */
    @Test
    public void cloneDirectoryTest() {
        // TODO: test cloneDirectory
    }

    /**
     * Test the property 'branch'
     */
    @Test
    public void branchTest() {
        // TODO: test branch
    }

    /**
     * Test the property 'ref'
     */
    @Test
    public void refTest() {
        // TODO: test ref
    }

    /**
     * Test the property 'creds'
     */
    @Test
    public void credsTest() {
        // TODO: test creds
    }

}
