/*
 * Argo Events
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.5.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.events.models.sensor;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for K8SResourcePolicy
 */
public class K8SResourcePolicyTest {
    private final K8SResourcePolicy model = new K8SResourcePolicy();

    /**
     * Model tests for K8SResourcePolicy
     */
    @Test
    public void testK8SResourcePolicy() {
        // TODO: test K8SResourcePolicy
    }

    /**
     * Test the property 'labels'
     */
    @Test
    public void labelsTest() {
        // TODO: test labels
    }

    /**
     * Test the property 'errorOnBackoffTimeout'
     */
    @Test
    public void errorOnBackoffTimeoutTest() {
        // TODO: test errorOnBackoffTimeout
    }

    /**
     * Test the property 'backoff'
     */
    @Test
    public void backoffTest() {
        // TODO: test backoff
    }

}
