/*
 * Argo Events
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.events.models.sensor;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.events.models.sensor.TriggerParameter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for KafkaTrigger
 */
public class KafkaTriggerTest {
    private final KafkaTrigger model = new KafkaTrigger();

    /**
     * Model tests for KafkaTrigger
     */
    @Test
    public void testKafkaTrigger() {
        // TODO: test KafkaTrigger
    }

    /**
     * Test the property 'tls'
     */
    @Test
    public void tlsTest() {
        // TODO: test tls
    }

    /**
     * Test the property 'partitioningKey'
     */
    @Test
    public void partitioningKeyTest() {
        // TODO: test partitioningKey
    }

    /**
     * Test the property 'parameters'
     */
    @Test
    public void parametersTest() {
        // TODO: test parameters
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'partition'
     */
    @Test
    public void partitionTest() {
        // TODO: test partition
    }

    /**
     * Test the property 'compress'
     */
    @Test
    public void compressTest() {
        // TODO: test compress
    }

    /**
     * Test the property 'topic'
     */
    @Test
    public void topicTest() {
        // TODO: test topic
    }

    /**
     * Test the property 'requiredAcks'
     */
    @Test
    public void requiredAcksTest() {
        // TODO: test requiredAcks
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'flushFrequency'
     */
    @Test
    public void flushFrequencyTest() {
        // TODO: test flushFrequency
    }

    /**
     * Test the property 'sasl'
     */
    @Test
    public void saslTest() {
        // TODO: test sasl
    }

    /**
     * Test the property 'payload'
     */
    @Test
    public void payloadTest() {
        // TODO: test payload
    }

}
