/*
 * Argo Events
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.events.models.eventbus;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.events.models.eventbus.ContainerTemplate;
import io.argoproj.events.models.eventbus.PersistenceStrategy;
import io.kubernetes.client.openapi.models.V1PodSecurityContext;
import io.kubernetes.client.openapi.models.V1Toleration;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for NativeStrategy
 */
public class NativeStrategyTest {
    private final NativeStrategy model = new NativeStrategy();

    /**
     * Model tests for NativeStrategy
     */
    @Test
    public void testNativeStrategy() {
        // TODO: test NativeStrategy
    }

    /**
     * Test the property 'antiAffinity'
     */
    @Test
    public void antiAffinityTest() {
        // TODO: test antiAffinity
    }

    /**
     * Test the property 'securityContext'
     */
    @Test
    public void securityContextTest() {
        // TODO: test securityContext
    }

    /**
     * Test the property 'replicas'
     */
    @Test
    public void replicasTest() {
        // TODO: test replicas
    }

    /**
     * Test the property 'maxAge'
     */
    @Test
    public void maxAgeTest() {
        // TODO: test maxAge
    }

    /**
     * Test the property 'metricsContainerTemplate'
     */
    @Test
    public void metricsContainerTemplateTest() {
        // TODO: test metricsContainerTemplate
    }

    /**
     * Test the property 'nodeSelector'
     */
    @Test
    public void nodeSelectorTest() {
        // TODO: test nodeSelector
    }

    /**
     * Test the property 'auth'
     */
    @Test
    public void authTest() {
        // TODO: test auth
    }

    /**
     * Test the property 'containerTemplate'
     */
    @Test
    public void containerTemplateTest() {
        // TODO: test containerTemplate
    }

    /**
     * Test the property 'tolerations'
     */
    @Test
    public void tolerationsTest() {
        // TODO: test tolerations
    }

    /**
     * Test the property 'persistence'
     */
    @Test
    public void persistenceTest() {
        // TODO: test persistence
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

}
