/*
 * Argo Events
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.events.models.eventsource;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AMQPExchangeDeclareConfig
 */
public class AMQPExchangeDeclareConfigTest {
    private final AMQPExchangeDeclareConfig model = new AMQPExchangeDeclareConfig();

    /**
     * Model tests for AMQPExchangeDeclareConfig
     */
    @Test
    public void testAMQPExchangeDeclareConfig() {
        // TODO: test AMQPExchangeDeclareConfig
    }

    /**
     * Test the property 'durable'
     */
    @Test
    public void durableTest() {
        // TODO: test durable
    }

    /**
     * Test the property 'internal'
     */
    @Test
    public void internalTest() {
        // TODO: test internal
    }

    /**
     * Test the property 'noWait'
     */
    @Test
    public void noWaitTest() {
        // TODO: test noWait
    }

    /**
     * Test the property 'autoDelete'
     */
    @Test
    public void autoDeleteTest() {
        // TODO: test autoDelete
    }

}
