/*
 * Argo Events
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.events.models.eventsource;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kubernetes.client.openapi.models.V1SecretKeySelector;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for AzureEventsHubEventSource
 */
public class AzureEventsHubEventSourceTest {
    private final AzureEventsHubEventSource model = new AzureEventsHubEventSource();

    /**
     * Model tests for AzureEventsHubEventSource
     */
    @Test
    public void testAzureEventsHubEventSource() {
        // TODO: test AzureEventsHubEventSource
    }

    /**
     * Test the property 'sharedAccessKeyName'
     */
    @Test
    public void sharedAccessKeyNameTest() {
        // TODO: test sharedAccessKeyName
    }

    /**
     * Test the property 'sharedAccessKey'
     */
    @Test
    public void sharedAccessKeyTest() {
        // TODO: test sharedAccessKey
    }

    /**
     * Test the property 'hubName'
     */
    @Test
    public void hubNameTest() {
        // TODO: test hubName
    }

    /**
     * Test the property 'fqdn'
     */
    @Test
    public void fqdnTest() {
        // TODO: test fqdn
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

}
