/*
 * Argo Events
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.events.models.eventsource;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.events.models.eventsource.WebhookContext;
import io.kubernetes.client.openapi.models.V1SecretKeySelector;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BitbucketServerEventSource
 */
public class BitbucketServerEventSourceTest {
    private final BitbucketServerEventSource model = new BitbucketServerEventSource();

    /**
     * Model tests for BitbucketServerEventSource
     */
    @Test
    public void testBitbucketServerEventSource() {
        // TODO: test BitbucketServerEventSource
    }

    /**
     * Test the property 'repositorySlug'
     */
    @Test
    public void repositorySlugTest() {
        // TODO: test repositorySlug
    }

    /**
     * Test the property 'accessToken'
     */
    @Test
    public void accessTokenTest() {
        // TODO: test accessToken
    }

    /**
     * Test the property 'webhookSecret'
     */
    @Test
    public void webhookSecretTest() {
        // TODO: test webhookSecret
    }

    /**
     * Test the property 'webhook'
     */
    @Test
    public void webhookTest() {
        // TODO: test webhook
    }

    /**
     * Test the property 'bitbucketserverBaseURL'
     */
    @Test
    public void bitbucketserverBaseURLTest() {
        // TODO: test bitbucketserverBaseURL
    }

    /**
     * Test the property 'deleteHookOnFinish'
     */
    @Test
    public void deleteHookOnFinishTest() {
        // TODO: test deleteHookOnFinish
    }

    /**
     * Test the property 'events'
     */
    @Test
    public void eventsTest() {
        // TODO: test events
    }

    /**
     * Test the property 'projectKey'
     */
    @Test
    public void projectKeyTest() {
        // TODO: test projectKey
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

}
