/*
 * Argo Events
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.events.models.eventsource;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ConfigMapPersistence
 */
public class ConfigMapPersistenceTest {
    private final ConfigMapPersistence model = new ConfigMapPersistence();

    /**
     * Model tests for ConfigMapPersistence
     */
    @Test
    public void testConfigMapPersistence() {
        // TODO: test ConfigMapPersistence
    }

    /**
     * Test the property 'createIfNotExist'
     */
    @Test
    public void createIfNotExistTest() {
        // TODO: test createIfNotExist
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

}
