/*
 * Argo Events
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.events.models.eventsource;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.events.models.eventsource.AMQPEventSource;
import io.argoproj.events.models.eventsource.AzureEventsHubEventSource;
import io.argoproj.events.models.eventsource.CalendarEventSource;
import io.argoproj.events.models.eventsource.EmitterEventSource;
import io.argoproj.events.models.eventsource.FileEventSource;
import io.argoproj.events.models.eventsource.GenericEventSource;
import io.argoproj.events.models.eventsource.GithubEventSource;
import io.argoproj.events.models.eventsource.GitlabEventSource;
import io.argoproj.events.models.eventsource.HDFSEventSource;
import io.argoproj.events.models.eventsource.KafkaEventSource;
import io.argoproj.events.models.eventsource.MQTTEventSource;
import io.argoproj.events.models.eventsource.NATSEventsSource;
import io.argoproj.events.models.eventsource.NSQEventSource;
import io.argoproj.events.models.eventsource.PubSubEventSource;
import io.argoproj.events.models.eventsource.PulsarEventSource;
import io.argoproj.events.models.eventsource.RedisEventSource;
import io.argoproj.events.models.eventsource.ResourceEventSource;
import io.argoproj.events.models.eventsource.SNSEventSource;
import io.argoproj.events.models.eventsource.SQSEventSource;
import io.argoproj.events.models.eventsource.Service;
import io.argoproj.events.models.eventsource.SlackEventSource;
import io.argoproj.events.models.eventsource.StorageGridEventSource;
import io.argoproj.events.models.eventsource.StripeEventSource;
import io.argoproj.events.models.eventsource.Template;
import io.argoproj.events.models.eventsource.WebhookContext;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for EventSourceSpec
 */
public class EventSourceSpecTest {
    private final EventSourceSpec model = new EventSourceSpec();

    /**
     * Model tests for EventSourceSpec
     */
    @Test
    public void testEventSourceSpec() {
        // TODO: test EventSourceSpec
    }

    /**
     * Test the property 'gitlab'
     */
    @Test
    public void gitlabTest() {
        // TODO: test gitlab
    }

    /**
     * Test the property 'minio'
     */
    @Test
    public void minioTest() {
        // TODO: test minio
    }

    /**
     * Test the property 'kafka'
     */
    @Test
    public void kafkaTest() {
        // TODO: test kafka
    }

    /**
     * Test the property 'replica'
     */
    @Test
    public void replicaTest() {
        // TODO: test replica
    }

    /**
     * Test the property 'file'
     */
    @Test
    public void fileTest() {
        // TODO: test file
    }

    /**
     * Test the property 'nsq'
     */
    @Test
    public void nsqTest() {
        // TODO: test nsq
    }

    /**
     * Test the property 'pulsar'
     */
    @Test
    public void pulsarTest() {
        // TODO: test pulsar
    }

    /**
     * Test the property 'calendar'
     */
    @Test
    public void calendarTest() {
        // TODO: test calendar
    }

    /**
     * Test the property 'hdfs'
     */
    @Test
    public void hdfsTest() {
        // TODO: test hdfs
    }

    /**
     * Test the property 'amqp'
     */
    @Test
    public void amqpTest() {
        // TODO: test amqp
    }

    /**
     * Test the property 'service'
     */
    @Test
    public void serviceTest() {
        // TODO: test service
    }

    /**
     * Test the property 'generic'
     */
    @Test
    public void genericTest() {
        // TODO: test generic
    }

    /**
     * Test the property 'redis'
     */
    @Test
    public void redisTest() {
        // TODO: test redis
    }

    /**
     * Test the property 'mqtt'
     */
    @Test
    public void mqttTest() {
        // TODO: test mqtt
    }

    /**
     * Test the property 'template'
     */
    @Test
    public void templateTest() {
        // TODO: test template
    }

    /**
     * Test the property 'replicas'
     */
    @Test
    public void replicasTest() {
        // TODO: test replicas
    }

    /**
     * Test the property 'sqs'
     */
    @Test
    public void sqsTest() {
        // TODO: test sqs
    }

    /**
     * Test the property 'webhook'
     */
    @Test
    public void webhookTest() {
        // TODO: test webhook
    }

    /**
     * Test the property 'azureEventsHub'
     */
    @Test
    public void azureEventsHubTest() {
        // TODO: test azureEventsHub
    }

    /**
     * Test the property 'sns'
     */
    @Test
    public void snsTest() {
        // TODO: test sns
    }

    /**
     * Test the property 'emitter'
     */
    @Test
    public void emitterTest() {
        // TODO: test emitter
    }

    /**
     * Test the property 'pubSub'
     */
    @Test
    public void pubSubTest() {
        // TODO: test pubSub
    }

    /**
     * Test the property 'github'
     */
    @Test
    public void githubTest() {
        // TODO: test github
    }

    /**
     * Test the property 'resource'
     */
    @Test
    public void resourceTest() {
        // TODO: test resource
    }

    /**
     * Test the property 'slack'
     */
    @Test
    public void slackTest() {
        // TODO: test slack
    }

    /**
     * Test the property 'eventBusName'
     */
    @Test
    public void eventBusNameTest() {
        // TODO: test eventBusName
    }

    /**
     * Test the property 'nats'
     */
    @Test
    public void natsTest() {
        // TODO: test nats
    }

    /**
     * Test the property 'storageGrid'
     */
    @Test
    public void storageGridTest() {
        // TODO: test storageGrid
    }

    /**
     * Test the property 'stripe'
     */
    @Test
    public void stripeTest() {
        // TODO: test stripe
    }

}
