/*
 * Argo Events
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.events.models.eventsource;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kubernetes.client.openapi.models.V1ConfigMapKeySelector;
import io.kubernetes.client.openapi.models.V1SecretKeySelector;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for HDFSEventSource
 */
public class HDFSEventSourceTest {
    private final HDFSEventSource model = new HDFSEventSource();

    /**
     * Model tests for HDFSEventSource
     */
    @Test
    public void testHDFSEventSource() {
        // TODO: test HDFSEventSource
    }

    /**
     * Test the property 'krbUsername'
     */
    @Test
    public void krbUsernameTest() {
        // TODO: test krbUsername
    }

    /**
     * Test the property 'addresses'
     */
    @Test
    public void addressesTest() {
        // TODO: test addresses
    }

    /**
     * Test the property 'checkInterval'
     */
    @Test
    public void checkIntervalTest() {
        // TODO: test checkInterval
    }

    /**
     * Test the property 'krbCCacheSecret'
     */
    @Test
    public void krbCCacheSecretTest() {
        // TODO: test krbCCacheSecret
    }

    /**
     * Test the property 'krbRealm'
     */
    @Test
    public void krbRealmTest() {
        // TODO: test krbRealm
    }

    /**
     * Test the property 'hdfsUser'
     */
    @Test
    public void hdfsUserTest() {
        // TODO: test hdfsUser
    }

    /**
     * Test the property 'pathRegexp'
     */
    @Test
    public void pathRegexpTest() {
        // TODO: test pathRegexp
    }

    /**
     * Test the property 'krbServicePrincipalName'
     */
    @Test
    public void krbServicePrincipalNameTest() {
        // TODO: test krbServicePrincipalName
    }

    /**
     * Test the property 'directory'
     */
    @Test
    public void directoryTest() {
        // TODO: test directory
    }

    /**
     * Test the property 'path'
     */
    @Test
    public void pathTest() {
        // TODO: test path
    }

    /**
     * Test the property 'krbKeytabSecret'
     */
    @Test
    public void krbKeytabSecretTest() {
        // TODO: test krbKeytabSecret
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'krbConfigConfigMap'
     */
    @Test
    public void krbConfigConfigMapTest() {
        // TODO: test krbConfigConfigMap
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

}
