/*
 * Argo Events
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.events.models.eventsource;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kubernetes.client.openapi.models.V1SecretKeySelector;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PulsarEventSource
 */
public class PulsarEventSourceTest {
    private final PulsarEventSource model = new PulsarEventSource();

    /**
     * Model tests for PulsarEventSource
     */
    @Test
    public void testPulsarEventSource() {
        // TODO: test PulsarEventSource
    }

    /**
     * Test the property 'tls'
     */
    @Test
    public void tlsTest() {
        // TODO: test tls
    }

    /**
     * Test the property 'connectionBackoff'
     */
    @Test
    public void connectionBackoffTest() {
        // TODO: test connectionBackoff
    }

    /**
     * Test the property 'authTokenSecret'
     */
    @Test
    public void authTokenSecretTest() {
        // TODO: test authTokenSecret
    }

    /**
     * Test the property 'url'
     */
    @Test
    public void urlTest() {
        // TODO: test url
    }

    /**
     * Test the property 'jsonBody'
     */
    @Test
    public void jsonBodyTest() {
        // TODO: test jsonBody
    }

    /**
     * Test the property 'topics'
     */
    @Test
    public void topicsTest() {
        // TODO: test topics
    }

    /**
     * Test the property 'tlsTrustCertsSecret'
     */
    @Test
    public void tlsTrustCertsSecretTest() {
        // TODO: test tlsTrustCertsSecret
    }

    /**
     * Test the property 'tlsAllowInsecureConnection'
     */
    @Test
    public void tlsAllowInsecureConnectionTest() {
        // TODO: test tlsAllowInsecureConnection
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'tlsValidateHostname'
     */
    @Test
    public void tlsValidateHostnameTest() {
        // TODO: test tlsValidateHostname
    }

    /**
     * Test the property 'metadata'
     */
    @Test
    public void metadataTest() {
        // TODO: test metadata
    }

}
