/*
 * Argo Events
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.events.models.eventbus;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.events.models.eventbus.ContainerTemplate;
import io.argoproj.events.models.eventbus.PersistenceStrategy;
import io.kubernetes.client.openapi.models.V1Affinity;
import io.kubernetes.client.openapi.models.V1LocalObjectReference;
import io.kubernetes.client.openapi.models.V1PodSecurityContext;
import io.kubernetes.client.openapi.models.V1Toleration;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * NativeStrategy indicates to install a native NATS service
 */
@ApiModel(description = "NativeStrategy indicates to install a native NATS service")

public class NativeStrategy {
  public static final String SERIALIZED_NAME_PRIORITY_CLASS_NAME = "priorityClassName";
  @SerializedName(SERIALIZED_NAME_PRIORITY_CLASS_NAME)
  private String priorityClassName;

  public static final String SERIALIZED_NAME_SECURITY_CONTEXT = "securityContext";
  @SerializedName(SERIALIZED_NAME_SECURITY_CONTEXT)
  private V1PodSecurityContext securityContext = null;

  public static final String SERIALIZED_NAME_SERVICE_ACCOUNT_NAME = "serviceAccountName";
  @SerializedName(SERIALIZED_NAME_SERVICE_ACCOUNT_NAME)
  private String serviceAccountName;

  public static final String SERIALIZED_NAME_REPLICAS = "replicas";
  @SerializedName(SERIALIZED_NAME_REPLICAS)
  private Integer replicas;

  public static final String SERIALIZED_NAME_MAX_SUBS = "maxSubs";
  @SerializedName(SERIALIZED_NAME_MAX_SUBS)
  private Long maxSubs;

  public static final String SERIALIZED_NAME_MAX_AGE = "maxAge";
  @SerializedName(SERIALIZED_NAME_MAX_AGE)
  private String maxAge;

  public static final String SERIALIZED_NAME_AUTH = "auth";
  @SerializedName(SERIALIZED_NAME_AUTH)
  private String auth;

  public static final String SERIALIZED_NAME_MAX_BYTES = "maxBytes";
  @SerializedName(SERIALIZED_NAME_MAX_BYTES)
  private String maxBytes;

  public static final String SERIALIZED_NAME_PRIORITY = "priority";
  @SerializedName(SERIALIZED_NAME_PRIORITY)
  private Integer priority;

  public static final String SERIALIZED_NAME_NODE_SELECTOR = "nodeSelector";
  @SerializedName(SERIALIZED_NAME_NODE_SELECTOR)
  private Map<String, String> nodeSelector = null;

  public static final String SERIALIZED_NAME_AFFINITY = "affinity";
  @SerializedName(SERIALIZED_NAME_AFFINITY)
  private V1Affinity affinity = null;

  public static final String SERIALIZED_NAME_METRICS_CONTAINER_TEMPLATE = "metricsContainerTemplate";
  @SerializedName(SERIALIZED_NAME_METRICS_CONTAINER_TEMPLATE)
  private ContainerTemplate metricsContainerTemplate;

  public static final String SERIALIZED_NAME_CONTAINER_TEMPLATE = "containerTemplate";
  @SerializedName(SERIALIZED_NAME_CONTAINER_TEMPLATE)
  private ContainerTemplate containerTemplate;

  public static final String SERIALIZED_NAME_TOLERATIONS = "tolerations";
  @SerializedName(SERIALIZED_NAME_TOLERATIONS)
  private List<V1Toleration> tolerations = null;

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  private io.argoproj.events.models.common.Metadata metadata = null;

  public static final String SERIALIZED_NAME_IMAGE_PULL_SECRETS = "imagePullSecrets";
  @SerializedName(SERIALIZED_NAME_IMAGE_PULL_SECRETS)
  private List<V1LocalObjectReference> imagePullSecrets = null;

  public static final String SERIALIZED_NAME_PERSISTENCE = "persistence";
  @SerializedName(SERIALIZED_NAME_PERSISTENCE)
  private PersistenceStrategy persistence;

  public static final String SERIALIZED_NAME_MAX_MSGS = "maxMsgs";
  @SerializedName(SERIALIZED_NAME_MAX_MSGS)
  private Long maxMsgs;


  public NativeStrategy priorityClassName(String priorityClassName) {
    
    this.priorityClassName = priorityClassName;
    return this;
  }

   /**
   * If specified, indicates the EventSource pod&#39;s priority. \&quot;system-node-critical\&quot; and \&quot;system-cluster-critical\&quot; are two special keywords which indicate the highest priorities with the former being the highest priority. Any other name must be defined by creating a PriorityClass object with that name. If not specified, the pod priority will be default or zero if there is no default. More info: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/
   * @return priorityClassName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "If specified, indicates the EventSource pod's priority. \"system-node-critical\" and \"system-cluster-critical\" are two special keywords which indicate the highest priorities with the former being the highest priority. Any other name must be defined by creating a PriorityClass object with that name. If not specified, the pod priority will be default or zero if there is no default. More info: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/")

  public String getPriorityClassName() {
    return priorityClassName;
  }


  public void setPriorityClassName(String priorityClassName) {
    this.priorityClassName = priorityClassName;
  }


  public NativeStrategy securityContext(V1PodSecurityContext securityContext) {
    
    this.securityContext = securityContext;
    return this;
  }

   /**
   * Get securityContext
   * @return securityContext
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1PodSecurityContext getSecurityContext() {
    return securityContext;
  }


  public void setSecurityContext(V1PodSecurityContext securityContext) {
    this.securityContext = securityContext;
  }


  public NativeStrategy serviceAccountName(String serviceAccountName) {
    
    this.serviceAccountName = serviceAccountName;
    return this;
  }

   /**
   * ServiceAccountName to apply to NATS StatefulSet
   * @return serviceAccountName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "ServiceAccountName to apply to NATS StatefulSet")

  public String getServiceAccountName() {
    return serviceAccountName;
  }


  public void setServiceAccountName(String serviceAccountName) {
    this.serviceAccountName = serviceAccountName;
  }


  public NativeStrategy replicas(Integer replicas) {
    
    this.replicas = replicas;
    return this;
  }

   /**
   * Size is the NATS StatefulSet size
   * @return replicas
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Size is the NATS StatefulSet size")

  public Integer getReplicas() {
    return replicas;
  }


  public void setReplicas(Integer replicas) {
    this.replicas = replicas;
  }


  public NativeStrategy maxSubs(Long maxSubs) {
    
    this.maxSubs = maxSubs;
    return this;
  }

   /**
   * Maximum number of subscriptions per channel, 0 means unlimited. Defaults to 1000
   * @return maxSubs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Maximum number of subscriptions per channel, 0 means unlimited. Defaults to 1000")

  public Long getMaxSubs() {
    return maxSubs;
  }


  public void setMaxSubs(Long maxSubs) {
    this.maxSubs = maxSubs;
  }


  public NativeStrategy maxAge(String maxAge) {
    
    this.maxAge = maxAge;
    return this;
  }

   /**
   * Max Age of existing messages, i.e. \&quot;72h\&quot;, “4h35m”
   * @return maxAge
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Max Age of existing messages, i.e. \"72h\", “4h35m”")

  public String getMaxAge() {
    return maxAge;
  }


  public void setMaxAge(String maxAge) {
    this.maxAge = maxAge;
  }


  public NativeStrategy auth(String auth) {
    
    this.auth = auth;
    return this;
  }

   /**
   * Get auth
   * @return auth
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getAuth() {
    return auth;
  }


  public void setAuth(String auth) {
    this.auth = auth;
  }


  public NativeStrategy maxBytes(String maxBytes) {
    
    this.maxBytes = maxBytes;
    return this;
  }

   /**
   * Total size of messages per channel, 0 means unlimited. Defaults to 1GB
   * @return maxBytes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Total size of messages per channel, 0 means unlimited. Defaults to 1GB")

  public String getMaxBytes() {
    return maxBytes;
  }


  public void setMaxBytes(String maxBytes) {
    this.maxBytes = maxBytes;
  }


  public NativeStrategy priority(Integer priority) {
    
    this.priority = priority;
    return this;
  }

   /**
   * The priority value. Various system components use this field to find the priority of the EventSource pod. When Priority Admission Controller is enabled, it prevents users from setting this field. The admission controller populates this field from PriorityClassName. The higher the value, the higher the priority. More info: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/
   * @return priority
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The priority value. Various system components use this field to find the priority of the EventSource pod. When Priority Admission Controller is enabled, it prevents users from setting this field. The admission controller populates this field from PriorityClassName. The higher the value, the higher the priority. More info: https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/")

  public Integer getPriority() {
    return priority;
  }


  public void setPriority(Integer priority) {
    this.priority = priority;
  }


  public NativeStrategy nodeSelector(Map<String, String> nodeSelector) {
    
    this.nodeSelector = nodeSelector;
    return this;
  }

  public NativeStrategy putNodeSelectorItem(String key, String nodeSelectorItem) {
    if (this.nodeSelector == null) {
      this.nodeSelector = new HashMap<String, String>();
    }
    this.nodeSelector.put(key, nodeSelectorItem);
    return this;
  }

   /**
   * NodeSelector is a selector which must be true for the pod to fit on a node. Selector which must match a node&#39;s labels for the pod to be scheduled on that node. More info: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
   * @return nodeSelector
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "NodeSelector is a selector which must be true for the pod to fit on a node. Selector which must match a node's labels for the pod to be scheduled on that node. More info: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/")

  public Map<String, String> getNodeSelector() {
    return nodeSelector;
  }


  public void setNodeSelector(Map<String, String> nodeSelector) {
    this.nodeSelector = nodeSelector;
  }


  public NativeStrategy affinity(V1Affinity affinity) {
    
    this.affinity = affinity;
    return this;
  }

   /**
   * Get affinity
   * @return affinity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1Affinity getAffinity() {
    return affinity;
  }


  public void setAffinity(V1Affinity affinity) {
    this.affinity = affinity;
  }


  public NativeStrategy metricsContainerTemplate(ContainerTemplate metricsContainerTemplate) {
    
    this.metricsContainerTemplate = metricsContainerTemplate;
    return this;
  }

   /**
   * Get metricsContainerTemplate
   * @return metricsContainerTemplate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ContainerTemplate getMetricsContainerTemplate() {
    return metricsContainerTemplate;
  }


  public void setMetricsContainerTemplate(ContainerTemplate metricsContainerTemplate) {
    this.metricsContainerTemplate = metricsContainerTemplate;
  }


  public NativeStrategy containerTemplate(ContainerTemplate containerTemplate) {
    
    this.containerTemplate = containerTemplate;
    return this;
  }

   /**
   * Get containerTemplate
   * @return containerTemplate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ContainerTemplate getContainerTemplate() {
    return containerTemplate;
  }


  public void setContainerTemplate(ContainerTemplate containerTemplate) {
    this.containerTemplate = containerTemplate;
  }


  public NativeStrategy tolerations(List<V1Toleration> tolerations) {
    
    this.tolerations = tolerations;
    return this;
  }

  public NativeStrategy addTolerationsItem(V1Toleration tolerationsItem) {
    if (this.tolerations == null) {
      this.tolerations = new ArrayList<V1Toleration>();
    }
    this.tolerations.add(tolerationsItem);
    return this;
  }

   /**
   * If specified, the pod&#39;s tolerations.
   * @return tolerations
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "If specified, the pod's tolerations.")

  public List<V1Toleration> getTolerations() {
    return tolerations;
  }


  public void setTolerations(List<V1Toleration> tolerations) {
    this.tolerations = tolerations;
  }


  public NativeStrategy metadata(io.argoproj.events.models.common.Metadata metadata) {
    
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public io.argoproj.events.models.common.Metadata getMetadata() {
    return metadata;
  }


  public void setMetadata(io.argoproj.events.models.common.Metadata metadata) {
    this.metadata = metadata;
  }


  public NativeStrategy imagePullSecrets(List<V1LocalObjectReference> imagePullSecrets) {
    
    this.imagePullSecrets = imagePullSecrets;
    return this;
  }

  public NativeStrategy addImagePullSecretsItem(V1LocalObjectReference imagePullSecretsItem) {
    if (this.imagePullSecrets == null) {
      this.imagePullSecrets = new ArrayList<V1LocalObjectReference>();
    }
    this.imagePullSecrets.add(imagePullSecretsItem);
    return this;
  }

   /**
   * ImagePullSecrets is an optional list of references to secrets in the same namespace to use for pulling any of the images used by this PodSpec. If specified, these secrets will be passed to individual puller implementations for them to use. For example, in the case of docker, only DockerConfig type secrets are honored. More info: https://kubernetes.io/docs/concepts/containers/images#specifying-imagepullsecrets-on-a-pod
   * @return imagePullSecrets
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "ImagePullSecrets is an optional list of references to secrets in the same namespace to use for pulling any of the images used by this PodSpec. If specified, these secrets will be passed to individual puller implementations for them to use. For example, in the case of docker, only DockerConfig type secrets are honored. More info: https://kubernetes.io/docs/concepts/containers/images#specifying-imagepullsecrets-on-a-pod")

  public List<V1LocalObjectReference> getImagePullSecrets() {
    return imagePullSecrets;
  }


  public void setImagePullSecrets(List<V1LocalObjectReference> imagePullSecrets) {
    this.imagePullSecrets = imagePullSecrets;
  }


  public NativeStrategy persistence(PersistenceStrategy persistence) {
    
    this.persistence = persistence;
    return this;
  }

   /**
   * Get persistence
   * @return persistence
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PersistenceStrategy getPersistence() {
    return persistence;
  }


  public void setPersistence(PersistenceStrategy persistence) {
    this.persistence = persistence;
  }


  public NativeStrategy maxMsgs(Long maxMsgs) {
    
    this.maxMsgs = maxMsgs;
    return this;
  }

   /**
   * Maximum number of messages per channel, 0 means unlimited. Defaults to 1000000
   * @return maxMsgs
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Maximum number of messages per channel, 0 means unlimited. Defaults to 1000000")

  public Long getMaxMsgs() {
    return maxMsgs;
  }


  public void setMaxMsgs(Long maxMsgs) {
    this.maxMsgs = maxMsgs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NativeStrategy nativeStrategy = (NativeStrategy) o;
    return Objects.equals(this.priorityClassName, nativeStrategy.priorityClassName) &&
        Objects.equals(this.securityContext, nativeStrategy.securityContext) &&
        Objects.equals(this.serviceAccountName, nativeStrategy.serviceAccountName) &&
        Objects.equals(this.replicas, nativeStrategy.replicas) &&
        Objects.equals(this.maxSubs, nativeStrategy.maxSubs) &&
        Objects.equals(this.maxAge, nativeStrategy.maxAge) &&
        Objects.equals(this.auth, nativeStrategy.auth) &&
        Objects.equals(this.maxBytes, nativeStrategy.maxBytes) &&
        Objects.equals(this.priority, nativeStrategy.priority) &&
        Objects.equals(this.nodeSelector, nativeStrategy.nodeSelector) &&
        Objects.equals(this.affinity, nativeStrategy.affinity) &&
        Objects.equals(this.metricsContainerTemplate, nativeStrategy.metricsContainerTemplate) &&
        Objects.equals(this.containerTemplate, nativeStrategy.containerTemplate) &&
        Objects.equals(this.tolerations, nativeStrategy.tolerations) &&
        Objects.equals(this.metadata, nativeStrategy.metadata) &&
        Objects.equals(this.imagePullSecrets, nativeStrategy.imagePullSecrets) &&
        Objects.equals(this.persistence, nativeStrategy.persistence) &&
        Objects.equals(this.maxMsgs, nativeStrategy.maxMsgs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(priorityClassName, securityContext, serviceAccountName, replicas, maxSubs, maxAge, auth, maxBytes, priority, nodeSelector, affinity, metricsContainerTemplate, containerTemplate, tolerations, metadata, imagePullSecrets, persistence, maxMsgs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NativeStrategy {\n");
    sb.append("    priorityClassName: ").append(toIndentedString(priorityClassName)).append("\n");
    sb.append("    securityContext: ").append(toIndentedString(securityContext)).append("\n");
    sb.append("    serviceAccountName: ").append(toIndentedString(serviceAccountName)).append("\n");
    sb.append("    replicas: ").append(toIndentedString(replicas)).append("\n");
    sb.append("    maxSubs: ").append(toIndentedString(maxSubs)).append("\n");
    sb.append("    maxAge: ").append(toIndentedString(maxAge)).append("\n");
    sb.append("    auth: ").append(toIndentedString(auth)).append("\n");
    sb.append("    maxBytes: ").append(toIndentedString(maxBytes)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    nodeSelector: ").append(toIndentedString(nodeSelector)).append("\n");
    sb.append("    affinity: ").append(toIndentedString(affinity)).append("\n");
    sb.append("    metricsContainerTemplate: ").append(toIndentedString(metricsContainerTemplate)).append("\n");
    sb.append("    containerTemplate: ").append(toIndentedString(containerTemplate)).append("\n");
    sb.append("    tolerations: ").append(toIndentedString(tolerations)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    imagePullSecrets: ").append(toIndentedString(imagePullSecrets)).append("\n");
    sb.append("    persistence: ").append(toIndentedString(persistence)).append("\n");
    sb.append("    maxMsgs: ").append(toIndentedString(maxMsgs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

