/*
 * Argo Events
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.events.models.common;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kubernetes.client.openapi.models.V1SecretKeySelector;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TLSConfig
 */
public class TLSConfigTest {
    private final TLSConfig model = new TLSConfig();

    /**
     * Model tests for TLSConfig
     */
    @Test
    public void testTLSConfig() {
        // TODO: test TLSConfig
    }

    /**
     * Test the property 'clientKeyPath'
     */
    @Test
    public void clientKeyPathTest() {
        // TODO: test clientKeyPath
    }

    /**
     * Test the property 'clientKeySecret'
     */
    @Test
    public void clientKeySecretTest() {
        // TODO: test clientKeySecret
    }

    /**
     * Test the property 'clientCertPath'
     */
    @Test
    public void clientCertPathTest() {
        // TODO: test clientCertPath
    }

    /**
     * Test the property 'caCertSecret'
     */
    @Test
    public void caCertSecretTest() {
        // TODO: test caCertSecret
    }

    /**
     * Test the property 'caCertPath'
     */
    @Test
    public void caCertPathTest() {
        // TODO: test caCertPath
    }

    /**
     * Test the property 'clientCertSecret'
     */
    @Test
    public void clientCertSecretTest() {
        // TODO: test clientCertSecret
    }

}
