/*
 * Argo Events
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.events.models.common;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kubernetes.client.openapi.models.V1ConfigMapKeySelector;
import io.kubernetes.client.openapi.models.V1SecretKeySelector;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ValueFromSource
 */
public class ValueFromSourceTest {
    private final ValueFromSource model = new ValueFromSource();

    /**
     * Model tests for ValueFromSource
     */
    @Test
    public void testValueFromSource() {
        // TODO: test ValueFromSource
    }

    /**
     * Test the property 'secretKeyRef'
     */
    @Test
    public void secretKeyRefTest() {
        // TODO: test secretKeyRef
    }

    /**
     * Test the property 'configMapKeyRef'
     */
    @Test
    public void configMapKeyRefTest() {
        // TODO: test configMapKeyRef
    }

}
