/*
 * Argo Events
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.events.models.eventsource;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * AMQPConsumeConfig holds the configuration to immediately starts delivering queued messages
 */
@ApiModel(description = "AMQPConsumeConfig holds the configuration to immediately starts delivering queued messages")

public class AMQPConsumeConfig {
  public static final String SERIALIZED_NAME_EXCLUSIVE = "exclusive";
  @SerializedName(SERIALIZED_NAME_EXCLUSIVE)
  private Boolean exclusive;

  public static final String SERIALIZED_NAME_CONSUMER_TAG = "consumerTag";
  @SerializedName(SERIALIZED_NAME_CONSUMER_TAG)
  private String consumerTag;

  public static final String SERIALIZED_NAME_NO_WAIT = "noWait";
  @SerializedName(SERIALIZED_NAME_NO_WAIT)
  private Boolean noWait;

  public static final String SERIALIZED_NAME_NO_LOCAL = "noLocal";
  @SerializedName(SERIALIZED_NAME_NO_LOCAL)
  private Boolean noLocal;

  public static final String SERIALIZED_NAME_AUTO_ACK = "autoAck";
  @SerializedName(SERIALIZED_NAME_AUTO_ACK)
  private Boolean autoAck;


  public AMQPConsumeConfig exclusive(Boolean exclusive) {
    
    this.exclusive = exclusive;
    return this;
  }

   /**
   * Exclusive when true, the server will ensure that this is the sole consumer from this queue
   * @return exclusive
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Exclusive when true, the server will ensure that this is the sole consumer from this queue")

  public Boolean getExclusive() {
    return exclusive;
  }


  public void setExclusive(Boolean exclusive) {
    this.exclusive = exclusive;
  }


  public AMQPConsumeConfig consumerTag(String consumerTag) {
    
    this.consumerTag = consumerTag;
    return this;
  }

   /**
   * ConsumerTag is the identity of the consumer included in every delivery
   * @return consumerTag
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "ConsumerTag is the identity of the consumer included in every delivery")

  public String getConsumerTag() {
    return consumerTag;
  }


  public void setConsumerTag(String consumerTag) {
    this.consumerTag = consumerTag;
  }


  public AMQPConsumeConfig noWait(Boolean noWait) {
    
    this.noWait = noWait;
    return this;
  }

   /**
   * NowWait when true, do not wait for the server to confirm the request and immediately begin deliveries
   * @return noWait
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "NowWait when true, do not wait for the server to confirm the request and immediately begin deliveries")

  public Boolean getNoWait() {
    return noWait;
  }


  public void setNoWait(Boolean noWait) {
    this.noWait = noWait;
  }


  public AMQPConsumeConfig noLocal(Boolean noLocal) {
    
    this.noLocal = noLocal;
    return this;
  }

   /**
   * NoLocal flag is not supported by RabbitMQ
   * @return noLocal
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "NoLocal flag is not supported by RabbitMQ")

  public Boolean getNoLocal() {
    return noLocal;
  }


  public void setNoLocal(Boolean noLocal) {
    this.noLocal = noLocal;
  }


  public AMQPConsumeConfig autoAck(Boolean autoAck) {
    
    this.autoAck = autoAck;
    return this;
  }

   /**
   * AutoAck when true, the server will acknowledge deliveries to this consumer prior to writing the delivery to the network
   * @return autoAck
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "AutoAck when true, the server will acknowledge deliveries to this consumer prior to writing the delivery to the network")

  public Boolean getAutoAck() {
    return autoAck;
  }


  public void setAutoAck(Boolean autoAck) {
    this.autoAck = autoAck;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AMQPConsumeConfig amQPConsumeConfig = (AMQPConsumeConfig) o;
    return Objects.equals(this.exclusive, amQPConsumeConfig.exclusive) &&
        Objects.equals(this.consumerTag, amQPConsumeConfig.consumerTag) &&
        Objects.equals(this.noWait, amQPConsumeConfig.noWait) &&
        Objects.equals(this.noLocal, amQPConsumeConfig.noLocal) &&
        Objects.equals(this.autoAck, amQPConsumeConfig.autoAck);
  }

  @Override
  public int hashCode() {
    return Objects.hash(exclusive, consumerTag, noWait, noLocal, autoAck);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AMQPConsumeConfig {\n");
    sb.append("    exclusive: ").append(toIndentedString(exclusive)).append("\n");
    sb.append("    consumerTag: ").append(toIndentedString(consumerTag)).append("\n");
    sb.append("    noWait: ").append(toIndentedString(noWait)).append("\n");
    sb.append("    noLocal: ").append(toIndentedString(noLocal)).append("\n");
    sb.append("    autoAck: ").append(toIndentedString(autoAck)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

