/*
 * Argo Events
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.events.models.sensor;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.events.models.sensor.EventDependencyFilter;
import io.argoproj.events.models.sensor.EventDependencyTransformer;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * EventDependency describes a dependency
 */
@ApiModel(description = "EventDependency describes a dependency")

public class EventDependency {
  public static final String SERIALIZED_NAME_EVENT_SOURCE_NAME = "eventSourceName";
  @SerializedName(SERIALIZED_NAME_EVENT_SOURCE_NAME)
  private String eventSourceName;

  public static final String SERIALIZED_NAME_TRANSFORM = "transform";
  @SerializedName(SERIALIZED_NAME_TRANSFORM)
  private EventDependencyTransformer transform;

  public static final String SERIALIZED_NAME_EVENT_NAME = "eventName";
  @SerializedName(SERIALIZED_NAME_EVENT_NAME)
  private String eventName;

  public static final String SERIALIZED_NAME_FILTERS = "filters";
  @SerializedName(SERIALIZED_NAME_FILTERS)
  private EventDependencyFilter filters;

  public static final String SERIALIZED_NAME_FILTERS_LOGICAL_OPERATOR = "filtersLogicalOperator";
  @SerializedName(SERIALIZED_NAME_FILTERS_LOGICAL_OPERATOR)
  private String filtersLogicalOperator;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;


  public EventDependency eventSourceName(String eventSourceName) {
    
    this.eventSourceName = eventSourceName;
    return this;
  }

   /**
   * EventSourceName is the name of EventSource that Sensor depends on
   * @return eventSourceName
  **/
  @ApiModelProperty(required = true, value = "EventSourceName is the name of EventSource that Sensor depends on")

  public String getEventSourceName() {
    return eventSourceName;
  }


  public void setEventSourceName(String eventSourceName) {
    this.eventSourceName = eventSourceName;
  }


  public EventDependency transform(EventDependencyTransformer transform) {
    
    this.transform = transform;
    return this;
  }

   /**
   * Get transform
   * @return transform
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public EventDependencyTransformer getTransform() {
    return transform;
  }


  public void setTransform(EventDependencyTransformer transform) {
    this.transform = transform;
  }


  public EventDependency eventName(String eventName) {
    
    this.eventName = eventName;
    return this;
  }

   /**
   * EventName is the name of the event
   * @return eventName
  **/
  @ApiModelProperty(required = true, value = "EventName is the name of the event")

  public String getEventName() {
    return eventName;
  }


  public void setEventName(String eventName) {
    this.eventName = eventName;
  }


  public EventDependency filters(EventDependencyFilter filters) {
    
    this.filters = filters;
    return this;
  }

   /**
   * Get filters
   * @return filters
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public EventDependencyFilter getFilters() {
    return filters;
  }


  public void setFilters(EventDependencyFilter filters) {
    this.filters = filters;
  }


  public EventDependency filtersLogicalOperator(String filtersLogicalOperator) {
    
    this.filtersLogicalOperator = filtersLogicalOperator;
    return this;
  }

   /**
   * FiltersLogicalOperator defines how different filters are evaluated together. Available values: and (&amp;&amp;), or (||) Is optional and if left blank treated as and (&amp;&amp;).
   * @return filtersLogicalOperator
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "FiltersLogicalOperator defines how different filters are evaluated together. Available values: and (&&), or (||) Is optional and if left blank treated as and (&&).")

  public String getFiltersLogicalOperator() {
    return filtersLogicalOperator;
  }


  public void setFiltersLogicalOperator(String filtersLogicalOperator) {
    this.filtersLogicalOperator = filtersLogicalOperator;
  }


  public EventDependency name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Name is a unique name of this dependency
   * @return name
  **/
  @ApiModelProperty(required = true, value = "Name is a unique name of this dependency")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventDependency eventDependency = (EventDependency) o;
    return Objects.equals(this.eventSourceName, eventDependency.eventSourceName) &&
        Objects.equals(this.transform, eventDependency.transform) &&
        Objects.equals(this.eventName, eventDependency.eventName) &&
        Objects.equals(this.filters, eventDependency.filters) &&
        Objects.equals(this.filtersLogicalOperator, eventDependency.filtersLogicalOperator) &&
        Objects.equals(this.name, eventDependency.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(eventSourceName, transform, eventName, filters, filtersLogicalOperator, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EventDependency {\n");
    sb.append("    eventSourceName: ").append(toIndentedString(eventSourceName)).append("\n");
    sb.append("    transform: ").append(toIndentedString(transform)).append("\n");
    sb.append("    eventName: ").append(toIndentedString(eventName)).append("\n");
    sb.append("    filters: ").append(toIndentedString(filters)).append("\n");
    sb.append("    filtersLogicalOperator: ").append(toIndentedString(filtersLogicalOperator)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

