/*
 * Argo Events
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.events.models.sensor;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.events.models.sensor.PayloadField;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * ExprFilter
 */

public class ExprFilter {
  public static final String SERIALIZED_NAME_EXPR = "expr";
  @SerializedName(SERIALIZED_NAME_EXPR)
  private String expr;

  public static final String SERIALIZED_NAME_FIELDS = "fields";
  @SerializedName(SERIALIZED_NAME_FIELDS)
  private List<PayloadField> fields = new ArrayList<PayloadField>();


  public ExprFilter expr(String expr) {
    
    this.expr = expr;
    return this;
  }

   /**
   * Expr refers to the expression that determines the outcome of the filter.
   * @return expr
  **/
  @ApiModelProperty(required = true, value = "Expr refers to the expression that determines the outcome of the filter.")

  public String getExpr() {
    return expr;
  }


  public void setExpr(String expr) {
    this.expr = expr;
  }


  public ExprFilter fields(List<PayloadField> fields) {
    
    this.fields = fields;
    return this;
  }

  public ExprFilter addFieldsItem(PayloadField fieldsItem) {
    this.fields.add(fieldsItem);
    return this;
  }

   /**
   * Fields refers to set of keys that refer to the paths within event payload.
   * @return fields
  **/
  @ApiModelProperty(required = true, value = "Fields refers to set of keys that refer to the paths within event payload.")

  public List<PayloadField> getFields() {
    return fields;
  }


  public void setFields(List<PayloadField> fields) {
    this.fields = fields;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExprFilter exprFilter = (ExprFilter) o;
    return Objects.equals(this.expr, exprFilter.expr) &&
        Objects.equals(this.fields, exprFilter.fields);
  }

  @Override
  public int hashCode() {
    return Objects.hash(expr, fields);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExprFilter {\n");
    sb.append("    expr: ").append(toIndentedString(expr)).append("\n");
    sb.append("    fields: ").append(toIndentedString(fields)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

