/*
 * Argo Events
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.6.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.events.models.sensor;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.events.models.sensor.TriggerParameter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * HTTPTrigger is the trigger for the HTTP request
 */
@ApiModel(description = "HTTPTrigger is the trigger for the HTTP request")

public class HTTPTrigger {
  public static final String SERIALIZED_NAME_TLS = "tls";
  @SerializedName(SERIALIZED_NAME_TLS)
  private io.argoproj.events.models.common.TLSConfig tls = null;

  public static final String SERIALIZED_NAME_PARAMETERS = "parameters";
  @SerializedName(SERIALIZED_NAME_PARAMETERS)
  private List<TriggerParameter> parameters = null;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  private String url;

  public static final String SERIALIZED_NAME_BASIC_AUTH = "basicAuth";
  @SerializedName(SERIALIZED_NAME_BASIC_AUTH)
  private io.argoproj.events.models.common.BasicAuth basicAuth = null;

  public static final String SERIALIZED_NAME_METHOD = "method";
  @SerializedName(SERIALIZED_NAME_METHOD)
  private String method;

  public static final String SERIALIZED_NAME_HEADERS = "headers";
  @SerializedName(SERIALIZED_NAME_HEADERS)
  private Map<String, String> headers = null;

  public static final String SERIALIZED_NAME_SECURE_HEADERS = "secureHeaders";
  @SerializedName(SERIALIZED_NAME_SECURE_HEADERS)
  private List<io.argoproj.events.models.common.SecureHeader> secureHeaders = null;

  public static final String SERIALIZED_NAME_TIMEOUT = "timeout";
  @SerializedName(SERIALIZED_NAME_TIMEOUT)
  private Long timeout;

  public static final String SERIALIZED_NAME_PAYLOAD = "payload";
  @SerializedName(SERIALIZED_NAME_PAYLOAD)
  private List<TriggerParameter> payload = new ArrayList<TriggerParameter>();


  public HTTPTrigger tls(io.argoproj.events.models.common.TLSConfig tls) {
    
    this.tls = tls;
    return this;
  }

   /**
   * Get tls
   * @return tls
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public io.argoproj.events.models.common.TLSConfig getTls() {
    return tls;
  }


  public void setTls(io.argoproj.events.models.common.TLSConfig tls) {
    this.tls = tls;
  }


  public HTTPTrigger parameters(List<TriggerParameter> parameters) {
    
    this.parameters = parameters;
    return this;
  }

  public HTTPTrigger addParametersItem(TriggerParameter parametersItem) {
    if (this.parameters == null) {
      this.parameters = new ArrayList<TriggerParameter>();
    }
    this.parameters.add(parametersItem);
    return this;
  }

   /**
   * Parameters is the list of key-value extracted from event&#39;s payload that are applied to the HTTP trigger resource.
   * @return parameters
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Parameters is the list of key-value extracted from event's payload that are applied to the HTTP trigger resource.")

  public List<TriggerParameter> getParameters() {
    return parameters;
  }


  public void setParameters(List<TriggerParameter> parameters) {
    this.parameters = parameters;
  }


  public HTTPTrigger url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * URL refers to the URL to send HTTP request to.
   * @return url
  **/
  @ApiModelProperty(required = true, value = "URL refers to the URL to send HTTP request to.")

  public String getUrl() {
    return url;
  }


  public void setUrl(String url) {
    this.url = url;
  }


  public HTTPTrigger basicAuth(io.argoproj.events.models.common.BasicAuth basicAuth) {
    
    this.basicAuth = basicAuth;
    return this;
  }

   /**
   * Get basicAuth
   * @return basicAuth
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public io.argoproj.events.models.common.BasicAuth getBasicAuth() {
    return basicAuth;
  }


  public void setBasicAuth(io.argoproj.events.models.common.BasicAuth basicAuth) {
    this.basicAuth = basicAuth;
  }


  public HTTPTrigger method(String method) {
    
    this.method = method;
    return this;
  }

   /**
   * Method refers to the type of the HTTP request. Refer https://golang.org/src/net/http/method.go for more info. Default value is POST.
   * @return method
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Method refers to the type of the HTTP request. Refer https://golang.org/src/net/http/method.go for more info. Default value is POST.")

  public String getMethod() {
    return method;
  }


  public void setMethod(String method) {
    this.method = method;
  }


  public HTTPTrigger headers(Map<String, String> headers) {
    
    this.headers = headers;
    return this;
  }

  public HTTPTrigger putHeadersItem(String key, String headersItem) {
    if (this.headers == null) {
      this.headers = new HashMap<String, String>();
    }
    this.headers.put(key, headersItem);
    return this;
  }

   /**
   * Headers for the HTTP request.
   * @return headers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Headers for the HTTP request.")

  public Map<String, String> getHeaders() {
    return headers;
  }


  public void setHeaders(Map<String, String> headers) {
    this.headers = headers;
  }


  public HTTPTrigger secureHeaders(List<io.argoproj.events.models.common.SecureHeader> secureHeaders) {
    
    this.secureHeaders = secureHeaders;
    return this;
  }

  public HTTPTrigger addSecureHeadersItem(io.argoproj.events.models.common.SecureHeader secureHeadersItem) {
    if (this.secureHeaders == null) {
      this.secureHeaders = new ArrayList<io.argoproj.events.models.common.SecureHeader>();
    }
    this.secureHeaders.add(secureHeadersItem);
    return this;
  }

   /**
   * Secure Headers stored in Kubernetes Secrets for the HTTP requests.
   * @return secureHeaders
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Secure Headers stored in Kubernetes Secrets for the HTTP requests.")

  public List<io.argoproj.events.models.common.SecureHeader> getSecureHeaders() {
    return secureHeaders;
  }


  public void setSecureHeaders(List<io.argoproj.events.models.common.SecureHeader> secureHeaders) {
    this.secureHeaders = secureHeaders;
  }


  public HTTPTrigger timeout(Long timeout) {
    
    this.timeout = timeout;
    return this;
  }

   /**
   * Timeout refers to the HTTP request timeout in seconds. Default value is 60 seconds.
   * @return timeout
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Timeout refers to the HTTP request timeout in seconds. Default value is 60 seconds.")

  public Long getTimeout() {
    return timeout;
  }


  public void setTimeout(Long timeout) {
    this.timeout = timeout;
  }


  public HTTPTrigger payload(List<TriggerParameter> payload) {
    
    this.payload = payload;
    return this;
  }

  public HTTPTrigger addPayloadItem(TriggerParameter payloadItem) {
    this.payload.add(payloadItem);
    return this;
  }

   /**
   * Get payload
   * @return payload
  **/
  @ApiModelProperty(required = true, value = "")

  public List<TriggerParameter> getPayload() {
    return payload;
  }


  public void setPayload(List<TriggerParameter> payload) {
    this.payload = payload;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HTTPTrigger htTPTrigger = (HTTPTrigger) o;
    return Objects.equals(this.tls, htTPTrigger.tls) &&
        Objects.equals(this.parameters, htTPTrigger.parameters) &&
        Objects.equals(this.url, htTPTrigger.url) &&
        Objects.equals(this.basicAuth, htTPTrigger.basicAuth) &&
        Objects.equals(this.method, htTPTrigger.method) &&
        Objects.equals(this.headers, htTPTrigger.headers) &&
        Objects.equals(this.secureHeaders, htTPTrigger.secureHeaders) &&
        Objects.equals(this.timeout, htTPTrigger.timeout) &&
        Objects.equals(this.payload, htTPTrigger.payload);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tls, parameters, url, basicAuth, method, headers, secureHeaders, timeout, payload);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HTTPTrigger {\n");
    sb.append("    tls: ").append(toIndentedString(tls)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    basicAuth: ").append(toIndentedString(basicAuth)).append("\n");
    sb.append("    method: ").append(toIndentedString(method)).append("\n");
    sb.append("    headers: ").append(toIndentedString(headers)).append("\n");
    sb.append("    secureHeaders: ").append(toIndentedString(secureHeaders)).append("\n");
    sb.append("    timeout: ").append(toIndentedString(timeout)).append("\n");
    sb.append("    payload: ").append(toIndentedString(payload)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

