/*
 * Argo Events
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.5.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.argoproj.events.models.sensor;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.argoproj.events.models.sensor.K8SResourcePolicy;
import io.argoproj.events.models.sensor.StatusPolicy;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * TriggerPolicy dictates the policy for the trigger retries
 */
@ApiModel(description = "TriggerPolicy dictates the policy for the trigger retries")

public class TriggerPolicy {
  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private StatusPolicy status;

  public static final String SERIALIZED_NAME_K8S = "k8s";
  @SerializedName(SERIALIZED_NAME_K8S)
  private K8SResourcePolicy k8s;


  public TriggerPolicy status(StatusPolicy status) {
    
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public StatusPolicy getStatus() {
    return status;
  }


  public void setStatus(StatusPolicy status) {
    this.status = status;
  }


  public TriggerPolicy k8s(K8SResourcePolicy k8s) {
    
    this.k8s = k8s;
    return this;
  }

   /**
   * Get k8s
   * @return k8s
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public K8SResourcePolicy getK8s() {
    return k8s;
  }


  public void setK8s(K8SResourcePolicy k8s) {
    this.k8s = k8s;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TriggerPolicy triggerPolicy = (TriggerPolicy) o;
    return Objects.equals(this.status, triggerPolicy.status) &&
        Objects.equals(this.k8s, triggerPolicy.k8s);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, k8s);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TriggerPolicy {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    k8s: ").append(toIndentedString(k8s)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

